# Generated by Django 4.1.5 on 2023-01-22 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR_EMPLOYEES', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR_EMPLOYEES.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='management',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR_EMPLOYEES.management'),
        ),
    ]
