# Generated by Django 4.1.5 on 2023-01-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HR_EMPLOYEES", "0004_alter_jobtitle_jobtitle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobtitle",
            name="JobTitle",
        ),
        migrations.AddField(
            model_name="jobtitle",
            name="the_JobTitle",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
    ]
