# Generated by Django 4.1.5 on 2023-01-26 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR_EMPLOYEES', '0005_remove_jobtitle_jobtitle_jobtitle_the_jobtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtitle',
            old_name='the_JobTitle',
            new_name='JobTitle',
        ),
        migrations.AlterField(
            model_name='daysoff',
            name='leave_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR_EMPLOYEES.daysofftypes'),
        ),
    ]
