# Generated by Django 4.1.5 on 2023-01-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_EMPLOYEES', '0006_rename_the_jobtitle_jobtitle_jobtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mother_name',
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='caontact_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contract_time',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emp_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emp_type',
            field=models.CharField(choices=[('Temp', 'Temporary'), ('perm', 'permanent')], default='perm', max_length=4),
        ),
        migrations.AddField(
            model_name='user',
            name='family_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.FileField(null=True, upload_to='images/uploads/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='CV',
            field=models.FileField(null=True, upload_to='images/uploads/'),
        ),
    ]
