# Generated by Django 4.1.5 on 2023-01-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_EMPLOYEES', '0007_remove_user_father_name_remove_user_mother_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contract_time',
            field=models.DateTimeField(null=True),
        ),
    ]
