# Generated by Django 4.1.5 on 2023-01-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_EMPLOYEES', '0009_alter_user_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contract_copy',
            field=models.FileField(null=True, upload_to='images/uploads/'),
        ),
        migrations.AddField(
            model_name='user',
            name='insurance',
            field=models.FileField(null=True, upload_to='images/uploads/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contract_time',
            field=models.DateField(null=True),
        ),
    ]
