# Generated by Django 4.1.5 on 2023-01-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_EMPLOYEES', '0010_user_contract_copy_user_insurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
