# Generated by Django 4.1.5 on 2023-01-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_EMPLOYEES', '0011_alter_user_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contract_time',
        ),
        migrations.AddField(
            model_name='user',
            name='the_contract_time',
            field=models.DateField(null=True),
        ),
    ]
