# Generated by Django 4.1.5 on 2023-01-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_EMPLOYEES', '0012_remove_user_contract_time_user_the_contract_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
