# Generated by Django 4.1.5 on 2023-01-28 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR_EMPLOYEES', '0013_alter_user_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daysofftypes',
            name='leave_en',
        ),
    ]
