# Generated by Django 4.1.5 on 2023-01-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_EMPLOYEES', '0018_alter_user_emp_type_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='family_relation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
