# Generated by Django 4.1.5 on 2023-01-30 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR_EMPLOYEES', '0023_management_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='user',
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR_EMPLOYEES.management'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR_EMPLOYEES.department'),
        ),
    ]
