# Generated by Django 4.1.5 on 2023-01-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR_EMPLOYEES', '0025_user_bank_account_iban_user_bank_account_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bank_account_name',
            new_name='bank_name',
        ),
    ]
