# Generated by Django 4.1.5 on 2023-01-30 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_EMPLOYEES', '0026_rename_bank_account_name_user_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='weakly_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('سبت', 'سبت'), ('احد', 'احد'), ('اثنين', 'اثنين'), ('ثلثاء', 'ثلثاء'), ('اربعاء', 'اربعاء'), ('خميس', 'خميس'), ('جمعه', 'جمعه')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
