# Generated by Django 4.1.5 on 2023-02-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_EMPLOYEES', '0031_alter_leave_request_the_leave_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_request',
            name='started_at',
            field=models.DateField(null=True),
        ),
    ]
