# Generated by Django 4.1.5 on 2023-02-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_EMPLOYEES', '0034_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_request',
            old_name='accepted',
            new_name='accepted_by_direct_manager',
        ),
        migrations.AddField(
            model_name='leave_request',
            name='accepted_by_hr_manager',
            field=models.BooleanField(null=True),
        ),
    ]
